run:
	python3 -m top.web_test_static


clean:
	rm -rf ./TAG_cuda_perform/results-*
	rm -rf ./TAG_cuda_function/results-*
	rm -rf ./TAG_cuda_syntax/results-*
	rm -rf ./TAG_profile_summary/results-*
	rm -rf ~/.cache/torch_extensions/py310_cu124/llm_kernel*
	rm -rf ~/.cache/torch_extensions/py310_cu124/target_kernel*
	rm -f ./nohup.out


